name: Expo Publish
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - v3
jobs:
  publish-web:
    name: Publish web version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install and Build üîß
        run: |
          yarn install
          yarn expo build:web
      - name: Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: web-build 
  publish-native:
    name: Publish native versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - uses: expo/expo-github-action@v6
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - run: |
          git config --global user.email "github-action@example.com"
          git config --global user.name "Github Bot"
          yarn version --new-version=$BUILD_VERSION
        env:
          BUILD_VERSION: 1.${{ github.run_id }}.${{ github.run_number }}
      - run: yarn install

      - run: echo $BUILD_VERSION

      # - run: eas build -p android --non-interactive

      - run: eas build -p ios --non-interactive
        env:
          EXPO_APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.EXPO_APPLE_APP_SPECIFIC_PASSWORD }}

      - run: eas submit --platform ios --non-interactive --latest
        env:
          EXPO_APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.EXPO_APPLE_APP_SPECIFIC_PASSWORD }}
